include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_constant: error
  language:
#    strict-casts: true
#    strict-inference: true

linter:
  rules:
    avoid_print: false
#    prefer_single_quotes: true
#    prefer_const_constructors: true
#    prefer_const_declarations: true
formatter:
    trailing_commas: preserve
